### ISSUE TITLE
Error: Failed to find a prefix name or keyword

### ISSUE THREAD

**Issue by clairececchini** [IC-FOODS/physical-activity-health-fitness#1]
When running make on [my ontology](https://github.com/IC-FOODS/physical-activity-health-fitness/blob/master/src/ontology/pahf-edit.owl) I get this error:

```
Chiaras-MacBook-Pro:ontology chiaracecchini$ make
/Users/chiaracecchini/ontology-starter-kit/bin/robot verify -i pahf-edit.owl --queries ../sparql/equivalent-classes-violation.sparql ../sparql/trailing-whitespace-violation.sparql ../sparql/owldef-self-reference-violation.sparql ../sparql/xref-syntax-violation.sparql ../sparql/nolabels-violation.sparql -O reports/
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$2 (file:/Users/chiaracecchini/ontology-starter-kit/bin/robot.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
ERROR [line: 1092, col: 48] Failed to find a prefix name or keyword: ’(8217;0x2019)
org.apache.jena.riot.RiotException: [line: 1092, col: 48] Failed to find a prefix name or keyword: ’(8217;0x2019)
	at org.apache.jena.riot.system.ErrorHandlerFactory$ErrorHandlerStd.fatal(ErrorHandlerFactory.java:136)
	at org.apache.jena.riot.lang.LangEngine.raiseException(LangEngine.java:163)
	at org.apache.jena.riot.lang.LangEngine.nextToken(LangEngine.java:106)
	at org.apache.jena.riot.lang.LangTurtleBase.triplesNode(LangTurtleBase.java:368)
	at org.apache.jena.riot.lang.LangTurtleBase.objectList(LangTurtleBase.java:350)
	at org.apache.jena.riot.lang.LangTurtleBase.predicateObjectItem(LangTurtleBase.java:288)
	at org.apache.jena.riot.lang.LangTurtleBase.predicateObjectList(LangTurtleBase.java:281)
	at org.apache.jena.riot.lang.LangTurtleBase.triples(LangTurtleBase.java:250)
	at org.apache.jena.riot.lang.LangTurtleBase.triplesSameSubject(LangTurtleBase.java:191)
	at org.apache.jena.riot.lang.LangTurtle.oneTopLevelElement(LangTurtle.java:47)
	at org.apache.jena.riot.lang.LangTurtleBase.runParser(LangTurtleBase.java:90)
	at org.apache.jena.riot.lang.LangBase.parse(LangBase.java:42)
	at org.apache.jena.riot.RDFParserRegistry$ReaderRIOTLang.read(RDFParserRegistry.java:185)
	at org.apache.jena.riot.RDFDataMgr.process(RDFDataMgr.java:906)
	at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:257)
	at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:231)
	at org.obolibrary.robot.QueryOperation.loadOntology(QueryOperation.java:40)
	at org.obolibrary.robot.VerifyCommand.execute(VerifyCommand.java:114)
	at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:219)
	at org.obolibrary.robot.CommandManager.execute(CommandManager.java:161)
	at org.obolibrary.robot.CommandManager.main(CommandManager.java:121)
	at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:53)
```

**Comment by clairececchini** [comment]
@mateolan can you please help on this one?

**Comment by clairececchini** [comment]
no longer giving error on the most recent version. Closing the issue
